app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'UserController@dashboard');

Route::get('lang/{lang}',['middleware'=>'web', function ($lang) {
    session(['lang' => $lang]);
    return \Redirect::back();
  }])->where([
      'lang' => 'en|es'
  ]);

Route::get('pdf/create_users_report', 'PdfController@create_users_report');
Route::get('excel/create_users_report', 'ExcelController@create_users_report');

// Authentication routes...
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');

Route::get('user/datatablesData', 'UserController@datatablesData');
Route::resource('user', 'UserController');
Route::get('patient/{id}/createStory', 'PatientController@createStory');
Route::get('patient/datatablesData', 'PatientController@datatablesData');
Route::resource('patient', 'PatientController');
Route::resource('story', 'StoryController');

app/Patient.php
<?php

namespace historiasclinicas;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'patients';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['dni', 'name', 'birthday', 'user_id'];

    public function stories()
    {
      return $this->hasMany('historiasclinicas\Story');
    }

    public function user()
    {
      return $this->belongsTo('historiasclinicas\User');
    }


}

app/Http/Controllers/PatientController.php
<?php

namespace historiasclinicas\Http\Controllers;

use Illuminate\Http\Request;

use historiasclinicas\Http\Requests;
use historiasclinicas\Http\Requests\PatientRequest;
use historiasclinicas\Http\Controllers\Controller;

use \historiasclinicas\Patient;
use \historiasclinicas\User;
use Carbon\Carbon;
use Auth;
use Yajra\Datatables\Datatables;
use Form;

class PatientController extends Controller
{
    public function __construct()
    {
      $this->middleware('auth');
      Carbon::setLocale('es');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if(Auth::user()->role=='admin'){
        $patients = Patient::paginate(10);
      }else{
        $patients = Patient::where('user_id',Auth::user()->id)->paginate(10);
      }

      return view('patient.index',compact('patients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->role=='admin'){
            $users = User::All();
            $data_users = User::lists('name','id');
        }else{
            $data_users = [Auth::user()->id => Auth::user()->name];
        }

        return view('patient.create',compact('data_users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PatientRequest $request)
    {
        if(Auth::user()->role=='doctor'){
            $request['user_id'] = Auth::user()->id;
        }
        Patient::create($request->all());
        return redirect('/patient')->with('status', 'Patiente Store!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(Auth::user()->role=='admin'){
          $patient = Patient::findOrFail($id);
        }else{
          $patient = Patient::where('id',$id)
                            ->where('user_id', Auth::user()->id)
                            ->firstOrFail();
        }

        return view('patient.show')->with(['patient' => $patient]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      if(Auth::user()->role=='admin'){
        $patient = Patient::findOrFail($id);
        $data_users = User::lists('name','id');
      }else{
        $patient = Patient::where('id',$id)
                          ->where('user_id', Auth::user()->id)
                          ->firstOrFail();
        $data_users = [Auth::user()->id => Auth::user()->name];
      }

      return view('patient.edit')->with(['patient' => $patient,'data_users' => $data_users]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PatientRequest $request, $id)
    {
        if(Auth::user()->role=='admin'){
            $patient = Patient::findOrFail($id);
        }else{
            $request['user_id'] = Auth::user()->id;
            $patient = Patient::where('id',$id)
                              ->where('user_id', Auth::user()->id)
                              ->firstOrFail();
        }

        $patient->fill($request->all());
        $patient->save();
        return redirect('/patient')->with('status', 'Patiente Save!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->role=='admin'){
            $patient = Patient::findOrFail($id);
        }else{
            $patient = Patient::where('id',$id)
                              ->where('user_id', Auth::user()->id)
                              ->firstOrFail();
        }
        $patient->delete();
        return redirect('/patient')->with('status', 'Patiente Delete!');
    }

    public function createStory($id){
      if(Auth::user()->role=='admin'){
        $patient = Patient::findOrFail($id);
      }else{
        $patient = Patient::where('id',$id)
                          ->where('user_id', Auth::user()->id)
                          ->firstOrFail();
      }
      return view('patient.createStory',['patient_id'=>$patient->id]);
    }

    public function datatablesData()
    {
        if(Auth::user()->role=='admin'){
          #return Datatables::of(Patient::query())->make(true);
          return Datatables::of(Patient::query())->addColumn('action', function ($patient) {
                      $algo = link_to_route('patient.edit', $title = 'Editar', $parameters = $patient->id, $attributes = ['class'=>'btn btn-primary']);
                      $algo .= link_to_route('patient.show', $title = 'Historia', $parameters = $patient->id, $attributes = ['class'=>'btn btn-info']);
                      $algo .= Form::open(['route' => ['patient.destroy',$patient->id] ,'method'=>'DELETE', 'style'=>'display:inline']);
                      $algo .= Form::submit('Eliminar',['class'=>'btn btn-danger']);
                      $algo .= Form::close();
                      return $algo;
                  })
                  ->make(true);
        }else{
          $patients = Patient::where('user_id',Auth::user()->id);
          #return Datatables::of($patients)->make(true);
          return Datatables::of($patients)->addColumn('action', function ($patient) {
                      $algo = link_to_route('patient.edit', $title = 'Editar', $parameters = $patient->id, $attributes = ['class'=>'btn btn-primary']);
                      $algo .= link_to_route('patient.show', $title = 'Historia', $parameters = $patient->id, $attributes = ['class'=>'btn btn-info']);
                      $algo .= Form::open(['route' => ['patient.destroy',$patient->id] ,'method'=>'DELETE', 'style'=>'display:inline']);
                      $algo .= Form::submit('Eliminar',['class'=>'btn btn-danger']);
                      $algo .= Form::close();
                      return $algo;
                  })
                  ->make(true);
        }
    }
}

resources/views/patient/create.blade.php
@extends('layouts.admin')
@section('module_title')
  Pacientes
@endsection
@section('section_title')
  Crear Paciente
@endsection
@section('content')
  @if(count($errors)>0)
  <div class="alert alert-danger text-center">
    <ul>
      @foreach($errors->all() as $error)
      <li>{!!$error!!}</li>
      @endforeach
    </ul>
  </div>
  @endif
  {!!Form::open(['route' => 'patient.store', 'method'=>'POST'])!!}
      <div class="form-group">
        {!!Form::label('DNI')!!}
        {!!Form::text('dni',null,['class'=>'form-control','placeholder'=>'ingresa el dni'])!!}
      </div>
      <div class="form-group">
        {!!Form::label('Nombre')!!}
        {!!Form::text('name',null,['class'=>'form-control','placeholder'=>'ingresa el nombre'])!!}
      </div>
      <div class="form-group">
        {!!Form::label('Nacimiento')!!}
        {!!Form::text('birthday',null,['class'=>'form-control','placeholder'=>'Fecha de nacimiento'])!!}
      </div>
      <div class="form-group">
        @if(Auth::user()->role=='admin')
        {!!Form::label('Doctor')!!}
        {!!Form::select('user_id', $data_users, null, ['class'=>'form-control','placeholder' => 'Seleccione un doctor...'])!!}
        @else
        {!!Form::select('user_id', $data_users, true, ['style'=>'display:none;'])!!}
        @endif
      </div>
      {!!Form::submit('Crear Paciente',['class'=>'btn btn-primary'])!!}
  {!!Form::close()!!}
@endsection

resources/views/patient/createStory.blade.php
@extends('layouts.admin')
@section('module_title')
  Pacientes
@endsection
@section('section_title')
  Crear Historia
@endsection
@section('content')
  @if(count($errors)>0)
  <div class="alert alert-danger text-center">
    <ul>
      @foreach($errors->all() as $error)
      <li>{!!$error!!}</li>
      @endforeach
    </ul>
  </div>
  @endif
  {!!Form::open(['route' => 'story.store', 'method'=>'POST'])!!}
    {!!Form::hidden('patient_id',$patient_id,null)!!}
      <div class="form-group">
        {!!Form::label('Historia')!!}
        {!!Form::textarea('story',null,['class'=>'form-control','placeholder'=>'ingresa la historia'])!!}
      </div>

      {!!Form::submit('Crear Paciente',['class'=>'btn btn-primary'])!!}
  {!!Form::close()!!}
@endsection

resources/views/patient/edit.blade.php
@extends('layouts.admin')
@section('module_title')
  Pacientes
@endsection
@section('section_title')
  Editar Paciente
@endsection
@section('content')
  @if(count($errors)>0)
  <div class="alert alert-danger text-center">
    <ul>
      @foreach($errors->all() as $error)
      <li>{!!$error!!}</li>
      @endforeach
    </ul>
  </div>
  @endif
  {!!Form::model($patient,['route' => ['patient.update',$patient->id], 'method'=>'PUT'])!!}
      <div class="form-group">
        {!!Form::label('DNI')!!}
        {!!Form::text('dni',null,['class'=>'form-control','placeholder'=>'ingresa el dni'])!!}
      </div>
      <div class="form-group">
        {!!Form::label('Nombre')!!}
        {!!Form::text('name',null,['class'=>'form-control','placeholder'=>'ingresa el nombre'])!!}
      </div>
      <div class="form-group">
        {!!Form::label('Nacimiento')!!}
        {!!Form::text('birthday',null,['class'=>'form-control','placeholder'=>'Fecha de nacimiento'])!!}
      </div>
      <div class="form-group">
        @if(Auth::user()->role=='admin')
        {!!Form::label('Doctor')!!}
        {!!Form::select('user_id', $data_users, null, ['class'=>'form-control','placeholder' => 'Seleccione un doctor...'])!!}
        @else
        {!!Form::select('user_id', $data_users, null, ['style'=>'display:none;'])!!}
        @endif
      </div>
      {!!Form::submit('Editar Paciente',['class'=>'btn btn-primary'])!!}
  {!!Form::close()!!}
@endsection

resources/views/patient/index.blade.php
@extends('layouts.admin')
@section('module_title')
  Pacientes
@endsection
@section('section_title')
  Ver Pacientes
@endsection
@section('content')
  @if (session('status'))
      <div class="alert alert-success">
          {{ session('status') }}
      </div>
  @endif
  @if(count($patients)==0)
    <div class="alert alert-danger text-center">
      No hay pacientes
    </div>
  @else
    <!--
    <table class='table'>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Dni</th>
          <th>Nacimiento</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody>
        @foreach($patients as $patient)
        <tr>
          <td>{{$patient->name}}</td>
          <td>{{$patient->dni}}</td>
          <td>{{$patient->birthday}}</td>
          <td>
            {!!link_to_route('patient.edit', $title = 'Editar', $parameters = $patient->id, $attributes = ['class'=>'btn btn-primary'])!!}
            {!!link_to_route('patient.show', $title = 'Historia', $parameters = $patient->id, $attributes = ['class'=>'btn btn-info'])!!}
            {!!Form::open(['route' => ['patient.destroy',$patient->id] ,'method'=>'DELETE', 'style'=>'display:inline'])!!}
              {!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
            {!!Form::close()!!}
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    {!!$patients->render()!!}
    -->
  @endif
  <table class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%" id="patients-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
@endsection

resources/views/patient/show.blade.php
@extends('layouts.admin')
@section('module_title')
  Pacientes
@endsection
@section('section_title')
  Ver Paciente
@endsection
@section('content')
  @if (session('status'))
      <div class="alert alert-success">
          {{ session('status') }}
      </div>
  @endif
  {!!link_to_action('PatientController@createStory', $title = 'Crear Historia', $parameters = $patient->id, $attributes = ['class'=>'btn btn-success'])!!}
  @if(count($patient->stories)==0)
    <div class="alert alert-danger text-center">
      No hay historias para este paciente.
    </div>
  @else
    <table class='table'>
      <thead>
        <tr>
          <th>Historia</th>
          <th>Fecha</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody>
        @foreach($patient->stories as $story)
        <tr>
          <td>{{$story->story}}</td>
          <td>{{$story->created_at->diffForHumans()}}</td>
          <td>
            {!!link_to_route('story.edit', $title = 'Editar', $parameters = $story->id, $attributes = ['class'=>'btn btn-primary'])!!}
            {!!Form::open(['route' => ['story.destroy',$story->id] ,'method'=>'DELETE', 'style'=>'display:inline'])!!}
              {!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
            {!!Form::close()!!}
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  @endif
@endsection